Vagrant.configure("2") do |config|

  config.vm.box = "{$opSystem}"
  config.vm.hostname = "{$hostName}"
  config.vm.network "public_network" , bridge: "{$bridgeNetCard}"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = {$cpuNum}
    vb.memory = "{$memNum}"
    vb.name = "{$hostName}"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo root:{$passWord} | chpasswd
    sed -i "s/PermitRootLogin without-password/PermitRootLogin yes/g" /etc/ssh/sshd_config
    sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
    ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"
    ps aux |grep sshd |grep -v grep |awk '{print $2}'  | xargs -i kill -9 {}
  SHELL

end
